---
name: Friendly Code Review Notifier
description: Friendly code review notifier based on the amount of open pull requests.
author: mxxlrfu
inputs:
  token:
    description: Repository Token
    default: ${{ github.token }}
  webhook:
    description: Webhook URL
  threshold:
    description: Emit a notification every n pull request is created
    default: 3
  limit:
    description: Limit of pull requests to attach to the notification (0 = unlimited)
    default: 1
runs:
  using: node16
  main: dist/index.js
