---
name: Friendly Code Review Notifier
description: Friendly code review notifier based on the amount of open pull requests.
author: mxxlrfu
inputs:
  token:
    description: Repository Token
    default: ${{ github.token }}
  webhook:
    description: Webhook URL
  threshold:
    default: 3
runs:
  using: node16
  main: dist/index.js
